analyzer:
  errors:
    missing_return: error
    dead_code: warning
linter:
  rules:
    - annotate_overrides
    - avoid_empty_else
    - avoid_print
    - cancel_subscriptions
    - curly_braces_in_flow_control_structures
    - close_sinks
    - collection_methods_unrelated_type
    - dangling_library_doc_comments
    - hash_and_equals
    - prefer_final_fields
    - public_member_api_docs
    - unrelated_type_equality_checks
    - valid_regexps
